[package]
name = "showbits-common"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
image.workspace = true
palette.workspace = true

[dependencies.taffy]
version = "0.4.0"
default-features = false
features = ["std", "taffy_tree", "flexbox", "grid", "block_layout"]

[lints]
workspace = true
