[workspace]
resolver = "2"
members = ["showbits-common", "showbits-thermal-printer"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
showbits-common.path = "./showbits-common"

[workspace.lints]
rust.unsafe_code = "forbid"
rust.future_incompatible = "warn"
rust.rust_2018_idioms = "warn"
rust.unused = "warn"
rust.noop_method_call = "warn"
rust.single_use_lifetimes = "warn"
clippy.use_self = "warn"

# Optimize dependencies in debug mode (mainly for faster image exports).
# Does not apply to workspace members, only "real" dependencies.
# https://doc.rust-lang.org/cargo/reference/profiles.html#overrides
[profile.dev.package."*"]
opt-level = 3
