[workspace]
resolver = "2"
members = ["showbits-common", "showbits-thermal-printer"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.80"
image = "0.24.9"
palette = "0.7.5"
showbits-common.path = "./showbits-common"

[workspace.dependencies.taffy]
version = "0.4.0"
default-features = false
features = ["std", "taffy_tree", "flexbox", "grid", "block_layout"]

[workspace.lints]
rust.unsafe_code = "forbid"
rust.future_incompatible = "warn"
rust.rust_2018_idioms = "warn"
rust.unused = "warn"
rust.noop_method_call = "warn"
rust.single_use_lifetimes = "warn"
clippy.use_self = "warn"

# Optimize dependencies in debug mode (mainly for faster image exports).
# Does not apply to workspace members, only "real" dependencies.
# https://doc.rust-lang.org/cargo/reference/profiles.html#overrides
[profile.dev.package."*"]
opt-level = 3
