[package]
name = "showbits-thermal-printer"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum = { version = "0.7.4", features = ["multipart"] }
clap = { version = "4.5.1", features = ["derive", "deprecated"] }
cosmic-text.workspace = true
escpos = { version = "0.7.2", features = ["full"] }
image.workspace = true
mime_guess = "2.0.4"
palette.workspace = true
rand = "0.8.5"
rust-embed = "8.3.0"
serde = { version = "1.0.197", features = ["derive"] }
showbits-assets.workspace = true
showbits-common.workspace = true
taffy.workspace = true
time = "0.3.34"
tokio = { version = "1.36.0", features = ["full"] }

[lints]
workspace = true
